### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by SsbThatsMe** [Redex68/CoVRt#9]

**Comment by RubberHux** [comment]
How do we present a main menu to both players? Do both need to agree on an option to begin playing?

**Comment by Redex68** [comment]
If it's local then I'd say only one needs to press start, easiest if it's the desktop player. For the main menu maybe we can steal something like this from my project?
https://youtu.be/Jr3EbiRdfd0 (the start shows the menu)
Basically just have something for the VR player to do before the game itself starts.
